export const NEXT_STEP = 'app/Checkout/step/NEXT_STEP'
export const UPDATE_STEP = 'app/Checkout/step/UPDATE_STEP'

export const POST_ADRESS = 'app/Checkout/adress/POST_ADRESS'
export const POST_ADRESS_ERROR = 'app/Checkout/adress/POST_ADRESS_ERROR'
export const POST_ADRESS_LOADED = 'app/Checkout/adress/POST_ADRESS_LOADED'
export const SET_ADRESS = 'app/Checkout/adress/SET_ADRESS'
export const SET_ADRESS_EQUAL = 'app/Checkout/adress/SET_ADRESS_EQUAL'
export const SET_COUNTRY_ADRESS = 'app/Checkout/adress/SET_COUNTRY_ADRESS'

export const GET_CLIENT = 'app/Checkout/client/GET_CLIENT'
export const USE_CLIENT_EXIST = 'app/Checkout/client/USE_CLIENT_EXIST'
export const GET_CLIENT_LOADED = 'app/Checkout/client/GET_CLIENT_LOADED'
export const GET_CLIENT_ERROR = 'app/Checkout/client/GET_CLIENT_ERROR'
export const POST_CLIENT = 'app/Checkout/client/POST_CLIENT'
export const POST_CLIENT_ERROR = 'app/Checkout/client/POST_CLIENT_ERROR'
export const POST_CLIENT_LOADED = 'app/Checkout/client/POST_CLIENT_LOADED'
export const SET_CLIENT_EMAIL = 'app/Checkout/client/SET_CLIENT_EMAIL'

export const SET_OFFER_PARAMS = 'app/Checkout/offer/SET_OFFER_PARAMS'
export const GET_OFFERS_LIST = 'app/Checkout/offer/GET_OFFERS_LIST'
export const GET_OFFER_LOADED = 'app/Checkout/offer/GET_OFFER_LOADED'
export const GET_OFFER_ERROR = 'app/Checkout/offer/GET_OFFER_ERROR'
export const GET_OFFER = 'app/Checkout/offer/GET_OFFER'

export const POST_TOKEN = 'app/Checkout/token/POST_TOKEN'
export const POST_TOKEN_ERROR = 'app/Checkout/token/POST_TOKEN_ERROR'
export const POST_TOKEN_LOADED = 'app/Checkout/token/POST_TOKEN_LOADED'
export const SET_TOKEN_STRIPE = 'app/Checkout/token/SET_TOKEN_STRIPE'

export const POST_SUBSCRIPTION = 'app/Checkout/subcription/POST_SUBSCRIPTION'
